package atmtransaction;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class Login extends javax.swing.JFrame {

    Connection con; //db connection object 
    Statement st; //SQL statement object
    LoginAttemptManager attemptManager = new LoginAttemptManager(); //instance of LoginAttemptManager class
    
    //constructor to initialize GUI components and establish database connection
    public Login() {
        initComponents();
        con = DBConnection.getConnection();
        try {
            if(con != null) {
                st = con.createStatement(); //initialize SQL statement object
            }
        }catch (SQLException e) {
             Logger.getLogger(Warning.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
    //method to handle user login
    public void login() {
        //get user inputs 
        String accountNumber = jTextAccNum.getText();
        String PIN = jPasswordField.getText();
        
        try {
            //check if the account number exists and is locked
            String checkLockSql = "SELECT locked_at FROM account WHERE account_number = '" + accountNumber + "'";
            ResultSet rsCheckLock = st.executeQuery(checkLockSql);
            
            //check if account is locked
            if(rsCheckLock.next()) {
                String lockedAt = rsCheckLock.getString("locked_at");
                //if account is locked, notify the user and display unlock time
                if(attemptManager.isAccountLocked(accountNumber, lockedAt)) {
                LocalDateTime lockedTime = LocalDateTime.parse(lockedAt, DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
                LocalDateTime unlockTime = lockedTime.plusHours(24);
                JOptionPane.showMessageDialog(this, "Your account is locked. It will be unlocked on " 
                        + unlockTime.format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")) + ".");
                jTextAccNum.setText("");
                jPasswordField.setText("");
                return;
                }
            }else{ //if account number doesn't exist
                JOptionPane.showMessageDialog(this, "Invalid Account Number. Please try again.");
                jTextAccNum.setText("");
                jPasswordField.setText("");
                return;
            }
            
            //authenticate user's credentials 
            String sql = "SELECT * from account WHERE account_number = '" + accountNumber + "' and pin = '" + PIN + "'";
            ResultSet rs = st.executeQuery(sql);
            
            //if credentials are valid
            if(rs.next()) {
                //reset failed attempts
                attemptManager.resetAttempts(accountNumber);
                String resetLock = "UPDATE account SET locked_at = NULL WHERE account_number = '" + accountNumber + "'";
                st.executeUpdate(resetLock);
            
                //proceed to the next screen
                Warning warningScreen = new Warning(accountNumber);
                warningScreen.setVisible(true);
                this.dispose();
            }else{ //if login fails
                //increment failed login attempts
                attemptManager.incrementAttempts(accountNumber, st);
                
                //lock the account after 3 failed attempts
                if(attemptManager.isAccountLocked(accountNumber, null)) {
                    String lockAccount = "UPDATE account SET locked_at = NOW() WHERE account_number = '" + accountNumber + "'";
                    st.executeUpdate(lockAccount);
                    JOptionPane.showMessageDialog(this, "Your account has been locked due to multiple failed"
                            + " login attempts. Please contact customer service.");
                }else{
                    JOptionPane.showMessageDialog(this, "Invalid PIN. Please try again.");
                    jPasswordField.setText("");
                }
            }
        }catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelAccNum = new javax.swing.JLabel();
        jLabelPIN = new javax.swing.JLabel();
        jTextAccNum = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jButtonClear = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonEnter = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(950, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MEGA BANK");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MEGA POSSIBILITIES");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logocopy.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel3)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 450, 500);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("WELCOME TO MEGA BANK ATM");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(520, 40, 370, 32);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setText("PLEASE ENTER YOUR ACCOUNT");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(570, 100, 290, 27);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setText("NUMBER AND PIN");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(630, 130, 170, 27);

        jLabelAccNum.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabelAccNum.setText("ACCOUNT NO.:");
        getContentPane().add(jLabelAccNum);
        jLabelAccNum.setBounds(500, 210, 150, 20);

        jLabelPIN.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabelPIN.setText("PIN:");
        getContentPane().add(jLabelPIN);
        jLabelPIN.setBounds(610, 270, 40, 27);

        jTextAccNum.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(jTextAccNum);
        jTextAccNum.setBounds(660, 200, 250, 40);

        jPasswordField.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(jPasswordField);
        jPasswordField.setBounds(660, 260, 250, 40);

        jButtonClear.setBackground(new java.awt.Color(255, 255, 0));
        jButtonClear.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jButtonClear.setText("CLEAR");
        jButtonClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClear);
        jButtonClear.setBounds(620, 360, 140, 60);

        jButtonCancel.setBackground(new java.awt.Color(255, 0, 0));
        jButtonCancel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jButtonCancel.setText("CANCEL");
        jButtonCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancel);
        jButtonCancel.setBounds(460, 360, 140, 60);

        jButtonEnter.setBackground(new java.awt.Color(0, 204, 51));
        jButtonEnter.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jButtonEnter.setText("ENTER");
        jButtonEnter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEnter);
        jButtonEnter.setBounds(780, 360, 140, 60);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(450, 0, 500, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        //"CANCEL" btn: closes the program
        System.exit(0); 
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        //"CLEAR" btn: clear input fields
        jTextAccNum.setText("");
        jPasswordField.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterActionPerformed
        //"ENTER" btn: calls login method
        login();
    }//GEN-LAST:event_jButtonEnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelAccNum;
    private javax.swing.JLabel jLabelPIN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextAccNum;
    // End of variables declaration//GEN-END:variables

}
